config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/movies", to: "movies#index", as: "movies"
  post "/movies", to: "movies#create"
  get "/movies/new", to: "movies#new", as: "new_movie"
  get "/movies/:id", to: "movies#show", as: "movie"

  put "/movies/:id", to: "movies#update"
  patch "/movies/:id", to: "movies#update"
  get "/movies/:id/edit", to: "movies#edit", as: "edit_movie"
  
  delete '/movies/:id', to: "movies#destroy", as: "delete_movie"
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
  
  def create
    @movie = Movie.new(movie_params)
    
    if @movie.save
      flash[:notice] = "Movie was succesfully saved"
      redirect_to @movie
    else
      render 'new'
    end
  end
  
  def new
    @movie = Movie.new
  end
  
  def show
    @movie = Movie.find(params[:id])
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def update  
    @movie = Movie.find(params[:id])
    
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
 
    redirect_to movies_path
  end
  
  private

  def movie_params
    params.permit(:title, :description, :rating)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# <a class="navbar-brand" href="#">Navbar</a> %>
  <%= link_to "Movies", movies_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMovieForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<form action="<%= movie_path(params[:id]) %>" method="POST" >
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <input type="hidden" name="_method" value="patch" />

    <label>Title</label>
    <input type="text" name="title" value="<%= @movie.title %>"  />

    <label>Description</label>
    <input type="textarea" name="description"  value="<%= @movie.description %>"  />

    <label>Rating</label>
    <input type="number" name="rating" min="1" max="10" value="<%= @movie.rating %>"  />

    <input type="submit" value="Update" />
</form>

app/views/movies/index.html.erb
<ul>
    <% @movies.each_with_index do |movie, index| %>
        <p>
            <%= movie.title %> - <%= movie.rating %> 
            <%= link_to "show", movie_path(movie) %>
            <%= link_to "edit", edit_movie_path(movie) %>
            <%= link_to 'delete', movie_path(movie),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</ul>

<%= link_to "Creat New Movie", new_movie_path %>

app/views/movies/new.html.erb
<h1>Create A New Movie</h1>

<form action="<%= movies_path %>" method="POST" >
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
  <label>Title</label>
  <input type="text" name="title" />

  <label>Description</label>
  <input type="textarea" name="description" />

  <label>Year</label>
  <input type="text">

  <label>Rating</label>
  <input type="number" name="rating" min="1" max="10" />

  <input type="submit" value="Create" />
</form>

app/views/movies/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h2><%= @movie["title"] %></h2>

<h2><%= @movie["description"] %></h2>

<h3>Rating</h3>
<p><%= @movie["rating"] %></p>

<%= link_to "Back", :back %>

<%= link_to "Edit", edit_movie_path %>